tango_with_django_project/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about$', views.about, name='about'),
    url(r'^like/$', views.like_category, name="like_category"),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    # url(r'^register/$', views.register, name="register"),
    # url(r'^login/$', views.user_login, name="login"),
    # url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^restricted/$', views.restricted, name="restricted"),
    url(r'^suggest/$', views.suggest_category, name="suggest_category"),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name="profile"),
    url(r'^profiles/$', views.list_profiles, name="list_profiles"),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/register_profile/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name="registration_register"),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0:
            self.views = 0
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    class Meta:
        verbose_name = "UserProfile"
        verbose_name_plural = "UserProfiles"

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from .models import Category, Page, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="please enter the category")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data

    class Meta:
        model = Page
        exclude = ('category',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=True)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user', )
    

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .models import Category, Page, UserProfile
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm
from datetime import datetime

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie
    request.session['act_user'] = str(request.user)
    request.session['meta'] = str(request.META)
    request.session['visits'] = visits

def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context=context_dict)
    return response

def about(request):
    context_dict = {}
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    visitor_cookie_handler(request)
    context_dict['act_user'] = request.session['act_user']
    print(request.user)
    context_dict['visits'] = request.session['visits']
    context_dict['meta'] = request.session['meta']
    response =  render(request, "rango/about.html", context_dict)
    return response

def show_category(request, category_name_slug):
    try:
        context_dict = {}
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
    if cat_id:
        cat = Category.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes = likes
            cat.save()
    return HttpResponse(likes)

def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)
    return render(request, 'rango/cats.html', {'cats': cat_list})



@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                profile.save()
                registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm
    return render(request, 'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                    'registered': registered,
                  })

def user_login(request):
    context_dict = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                context_dict['error'] = "Your Rango account is disable."
                return render(request, 'rango/login.html', context_dict)
                # return HttpResponse("Your Rango account is disabled.")
        else:
            context_dict['error'] = "Invalid login detils supplied."
            return render(request, 'rango/login.html', context_dict)
            # print("Invalid login details: {0}, {1}".format(username, password))
            # return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html', context_dict)

@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect('index')
        else:
            print(form.errors)
    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)

@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('profile', user.username)
        else:
            print(form.errors)
    return render(request, 'rango/profile.html', {"userprofile": userprofile, "selecteduser": user, "form": form})

@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    return render(request, 'rango/list_profiles.html', {"userprofile_list": userprofile_list})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

tango_with_django_project/templates/rango/about.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock title_block %}

{% block body_block %}
    <h1>About Rango</h1>
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango">
    <p>This tutorial has been put together by Rango</p>
    <button class="btn btn-primary" onclick="alert('You clicked the button using JS.');">JS Button</button>
    <button class="btn btn-primary" id="about-btn">JQuery Button</button>
    <p>This is an example.</p>
    <p>This is another example.</p>
    <p>User: {{ act_user }}</p>
    <p>Visits: {{ visits }}</p>
    <p>Meta: {{ meta }}</p>
    <img src="{{ MEDIA_URL }}cat.png" alt="Picutre of a cat">
{% endblock body_block %} 

tango_with_django_project/templates/rango/add_category.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{# {% load bootstrap_toolkit %} #}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title_block %}
    Add New Category
{% endblock title_block %}

{% block body_block %}
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        <h2 class="form-signin-heading">Add a Category</h2>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button class="btn btn-primary" type="submit" name="submi">{% bootstrap_icon "star" %}Create Category</button>
        {% endbuttons %}
    </form>
{% endblock body_block %}

tango_with_django_project/templates/rango/add_page.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}

{% block title_block %}
    Add New Page
{% endblock title_block %}

{% block body_block %}
    {% if category %}
        <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
        <h2 class="form-signin-heading">Add a Page</h2>
        <a href="{% url 'rango:show_category' category.slug %}">{{ categrory.name }}</a>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
        {% endfor %}
        <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
    </form>

    {% else %} 
    <p>This category does not exist.</p>
    {% endif %}
    

{% endblock body_block %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html>
<head lang="en">
    <meta charset="utf-8" />
    <title>Ranog - {% block title_block %}
        How to Tango with Django!
    {% endblock title_block %}</title>
</head>
<body>
<div>
    {% block sidebar_block %}
        {% get_category_list category %}
    {% endblock sidebar_block %}
</div>
{% block body_block %}
   <p>This is default content</p> 
{% endblock body_block %}
<hr/>
<div>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
            <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
        {% else %}
            <li><a href="{% url 'registration_register' %}">Sign up</a></li>
            <li><a href="{% url 'auth_login' %}">Login</a></li>
        {% endif %}
        
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>

    </ul>
</div>
</body>
</html>

tango_with_django_project/templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "images/favicon.ico" %}">

    <title>Rango - {% block title_block %}
      How to Tango with Django
    {% endblock title_block %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
      <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" aria-label="Toggle navigation"></button>
      <a class="navbar-brand" href="#">Rango</a>
      <div id="navbar">
        <nav class="nav navbar-nav float-xs-left">
          <a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
          {# <a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a> #}
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            <a class="nav-item nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
            <a class="nav-item nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>

            <a class="nav-item nav-link" href="{% url 'auth_logout' %}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'auth_login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'registration_register' %}">Sign up</a>
          {% endif %}
        </nav>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar_block %}
          <ul class="nav nav-list">
            <li class="nav-header">Type to find a category</li>
            <form>
              <li><input type="text" name="suggestion" class="input-medium search-query" value="" id="suggestion" /></li>
            </form>
          </ul>
          <hr>
          <div id='cats'>
          </div>
          <br />
          <p>All Categories</p>
            {% get_category_list category %}
          {% endblock sidebar_block %}
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
          {% block body_block %}
            
          {% endblock body_block %}
          
          
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js"></script>
    <script type="text/javascript" src="{% static "js/rango-jquery.js" %}"></script>
  </body>
</html>

tango_with_django_project/templates/rango/category.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock title_block %}

{% block body_block %}
<div>
    {% if category %}
        <h1>{{ category.name }}</h1>
            <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
                <button id="likes" data-catid="{{category.id}}" class="btn btn-primary btn-sm" type="button">
                    Like
                </button>
            {% endif %}
            </div>

        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in cateory.</strong>
        {% endif %}
        
        
    {% else %}
    <p>The specified category does not exist!</p>
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>    
    {% endif %}
</div>
{% endblock body_block %}

tango_with_django_project/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
            <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        
    {% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock title_block %}

{% block body_block %}
    

    <div class="jumbotron">
         <h1 class="display-3">Rango says...</h1>
        {% if user.is_authenticated %}
            <h1>Howdy {{ user.username }}</h1>
        {% else %}
            <h1>Hey there partner!</h1>
        {% endif %}
    </div>

<div class="row marketing">
    <div class="col-lg-6">
    <h4>Most Liked Categories</h4>
    <p>
        {% if categories %}
        <ul class="list-group">
            {% for category in categories %}
                <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </p>
    </div>

    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        <p>
            {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no pages in present.</strong>
            {% endif %}
        </p>

    </div>

</div>

    <p>Visits: {{ visits }}</p>
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango">
{% endblock body_block %}

tango_with_django_project/templates/rango/list_profiles.html
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}
{% block title_block %}
    User Profiles
{% endblock title_block %}

{% block body_block %}
    <h1>User Profile</h1>
    {% if userprofile_list %}
        <div class="panel-heading">
            <div class="panel-body">
                <div class="list-group">
                    {% for listuser in userprofile_list %}
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">
                                {% if listuser.user.userprofile.picture %}
                                       <img src="{{ MEDIA_URL }}{{ listuser.user.userprofile.picture }}" width="24" height="24">
                                {% else %}
                                <img src="http://lorempixel.com/64/64/people/" width="24" height="24">
                                {% endif %}
                                <a href="{% url 'rango:profile' listuser.user.username %}">
                                 {{ listuser.user.username }}   
                                </a>
                            </h4>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
    <p>There are no users for the site.</p>
    {% endif %}
{% endblock body_block %}

tango_with_django_project/templates/rango/login.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock title_block %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        {% if error %}
            {{ error }}
        {% endif %}
        Username: <input type="text" name="username" value="" size="50">
        Password: <input type="password" name="password" value="" size="50">
        <br />
        <input type="submit" name="submit">
    </form>
{% endblock body_block %}

tango_with_django_project/templates/rango/profile.html
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}
{% block title_block %}
    {{ selecteduser.username }} Profile
{% endblock title_block %}

{% block body_block %}
    <h1>{{ selecteduser.username }} Profile</h1>
    <img src="{{ MEDIA_URL }}{{ userprofile.picture }}" width="300" height="300" alt="{{ selecteduser.username}}" />
    <br />
    <div>
        {% if selecteduser.username == user.username %}
            <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />
            </form>
        {% else %}
            <p><strong>Website: </strong><a href="{{ userprofile.website }}">{{ userprofile.website }}</a></p>
        {% endif %}
    </div>
    <dir id="edit_profile"></dir>
{% endblock body_block %}

tango_with_django_project/templates/rango/profile_registration.html
{% extends "rango/base_bootstrap.html" %}

{% block title_block %}
    Registration - Step 2
{% endblock title_block %}

{% block body_block %}
    <h1>Registration - Step2</h1>
    <form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
{% endblock body_block %}

tango_with_django_project/templates/rango/register.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock title_block %}

{% block body_block %}
    <h1>About Page</h1>
    {% if registered %}
        Rango says: <strong>Thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage</a><br />
    {% else %}
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="submit" value="Register" / >
        </form>
    {% endif %}
{% endblock body_block %}

tango_with_django_project/templates/rango/restricted.html
{# {% extends "rango/base.html" %} #}
{% extends "rango/base_bootstrap.html" %}
{% load staticfiles %}

{% block title_block %}
    Restricted
{% endblock title_block %}

{% block body_block %}
    <p>since you are logged in, you can see this text!</p>
{% endblock body_block %}